#!/usr/bin/env zsh

#  $$$$$$$$\ $$\   $$\ $$\   $$\  $$$$$$\ $$$$$$$$\ $$$$$$\  $$$$$$\  $$\   $$\  $$$$$$\
#  $$  _____|$$ |  $$ |$$$\  $$ |$$  __$$\\__$$  __|\_$$  _|$$  __$$\ $$$\  $$ |$$  __$$\
#  $$ |      $$ |  $$ |$$$$\ $$ |$$ /  \__|  $$ |     $$ |  $$ /  $$ |$$$$\ $$ |$$ /  \__|
#  $$$$$\    $$ |  $$ |$$ $$\$$ |$$ |        $$ |     $$ |  $$ |  $$ |$$ $$\$$ |\$$$$$$\
#  $$  __|   $$ |  $$ |$$ \$$$$ |$$ |        $$ |     $$ |  $$ |  $$ |$$ \$$$$ | \____$$\
#  $$ |      $$ |  $$ |$$ |\$$$ |$$ |  $$\   $$ |     $$ |  $$ |  $$ |$$ |\$$$ |$$\   $$ |
#  $$ |      \$$$$$$  |$$ | \$$ |\$$$$$$  |  $$ |   $$$$$$\  $$$$$$  |$$ | \$$ |\$$$$$$  |
#  \__|       \______/ \__|  \__| \______/   \__|   \______| \______/ \__|  \__| \______/

# find shorthand
function f() {
    find . -name "$1"
}

# take this repo and copy it to somewhere else minus the .git stuff.
function gitexport(){
    mkdir -p "$1"
    git archive master | tar -x -C "$1"
}

# Streamlink functions
function slw() {
    streamlink -O "$1" best | tee "$2_$( date +%Y%m%d_%H%M%S ).ts" | vlc -
}

# Escape UTF-8 characters into their 3-byte format
function escape() {
    printf "\\\x%s" $(printf "$@" | xxd -p -c1 -u)
    echo # newline
}

# Switch DB enviroments
function sdb() {
    db_env=$1
    case ${db_env:u} in
        LOCAL)
            echo "Local"
            ln -sf [local DataSource] [DataSource]
            ;;
        QA3)
            echo "QA3"
            ln -sf [QA3 DataSource] [DataSource]
            ;;
        TESTING)
            echo "Testing"
            ln -sf [testing DataSource] [DataSource]
            ;;
        TRAINING)
            echo "Training"
            ln -sf [training DataSource] [DataSource]
            ;;
        *)
            echo "QA1"
            ln -sf [QA1 DataSource] [DataSource]
            ;;
    esac
}