#!/usr/bin/env bash

# Empty the Trash on all mounted volumes and the main HDD
# Also, clear Apple’s System Logs to improve shell startup speed
# Also, run periodic maintenence tasks
# Author: Artem Sapegin, sapegin.me
# License: MIT
# https://github.com/sapegin/dotfiles
echo Emptying trashes...
sudo rm -rfv $HOME/.Trash
sudo rm -rfv /Volumes/*/.Trashes;
sudo rm -rfv ~/.Trash;
echo Running all periodic maintenence tasks...;
sudo periodic daily weekly monthly;
echo Removing old logs...;
sudo rm -rfv /private/var/log/asl/*.asl;
sqlite3 ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV2 'delete from LSQuarantineEvent' >/dev/null 2>&1;
sqlite3 ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV2 'vacuum' >/dev/null 2>&1"
