
#    $$$$$$\  $$$$$$$\   $$$$$$\   $$$$$$\  $$$$$$$$\ $$\    $$\ $$$$$$\ $$\      $$\
#   $$  __$$\ $$  __$$\ $$  __$$\ $$  __$$\ $$  _____|$$ |   $$ |\_$$  _|$$$\    $$$ |
#   $$ /  \__|$$ |  $$ |$$ /  $$ |$$ /  \__|$$ |      $$ |   $$ |  $$ |  $$$$\  $$$$ |
#   \$$$$$$\  $$$$$$$  |$$$$$$$$ |$$ |      $$$$$\    \$$\  $$  |  $$ |  $$\$$\$$ $$ |
#    \____$$\ $$  ____/ $$  __$$ |$$ |      $$  __|    \$$\$$  /   $$ |  $$ \$$$  $$ |
#   $$\   $$ |$$ |      $$ |  $$ |$$ |  $$\ $$ |        \$$$  /    $$ |  $$ |\$  /$$ |
#   \$$$$$$  |$$ |      $$ |  $$ |\$$$$$$  |$$$$$$$$\    \$  /   $$$$$$\ $$ | \_/ $$ |
#    \______/ \__|      \__|  \__| \______/ \________|    \_/    \______|\__|     \__|



