#!/usr/bin/env bash

# Prefer US English and use UTF-8
export LANG="en_US"
export LC_ALL="en_US.UTF-8"

# Disable homebrew analytics
export HOMEBREW_NO_ANALYTICS=1

# pyenv enviroment variables
export PYENV_ROOT=/usr/local/var/pyenv

# Update your enviroment variables
export ANT_HOME=/usr/local/opt/ant
export MAVEN_HOME=/usr/local/opt/maven
export GRADLE_HOME=/usr/local/opt/gradle
# Gradle needs this.
export ANDROID_SDK_HOME=`echo $(brew --cellar)/android-sdk`
export ANDROID_NDK_HOME=`echo $(brew --cellar)/android-ndk`
export ANDROID_HOME=${ANDROID_SDK_HOME}
export PATH=$PATH:$ANDROID_HOME/tools/templates/gradle/wrapper

export JAVA_HOME=`/usr/libexec/java_home -v 1.8`

# For Hierarchy viewer
# Source https://developer.android.com/studio/profile/hierarchy-viewer-setup.html
export ANDROID_HVPROTO=ddm

# Larger bash history (allow 32³ entries; default is 500)
export HISTSIZE=32768
export HISTFILESIZE=$HISTSIZE
export HISTCONTROL="erasedups:ignoreboth"

# Make some commands not show up in history
export HISTIGNORE="ls:cd -:pwd:exit:date:* --help:&:[ ]*:bg:fg:history:clear"

export LS_COLORS='no=00:fi=00:di=01;34:ow=01;31:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.ogg=01;35:*.mp3=01;35:*.wav=01;35:'

# -------------------------------------------------------------------
# Color man pages:
# -------------------------------------------------------------------
export LESS_TERMCAP_mb=$'\E[01;31m'      # begin blinking
export LESS_TERMCAP_md=$'\E[01;31m'      # begin bold
export LESS_TERMCAP_me=$'\E[0m'          # end mode
export LESS_TERMCAP_se=$'\E[0m'          # end standout-mode
export LESS_TERMCAP_so=$'\E[01;44;33m'   # begin standout-mode - info box
export LESS_TERMCAP_ue=$'\E[0m'          # end underline
export LESS_TERMCAP_us=$'\E[01;32m'      # begin underline
