#!/usr/bin/env bash

#  $$$$$$$\   $$$$$$\ $$$$$$$$\ $$\   $$\
#  $$  __$$\ $$  __$$\\__$$  __|$$ |  $$ |
#  $$ |  $$ |$$ /  $$ |  $$ |   $$ |  $$ |
#  $$$$$$$  |$$$$$$$$ |  $$ |   $$$$$$$$ |
#  $$  ____/ $$  __$$ |  $$ |   $$  __$$ |
#  $$ |      $$ |  $$ |  $$ |   $$ |  $$ |
#  $$ |      $$ |  $$ |  $$ |   $$ |  $$ |
#  \__|      \__|  \__|  \__|   \__|  \__|

# Update your paths
export PATH=$GRADLE_HOME/bin:$PATH
export PATH=$MAVEN_HOME/bin:$PATH

#
# Will switch from miniconda to anaconda with next fresh install
# Switch export then
#
export PATH=~/miniconda3/bin:$PATH
#export PATH=~/anaconda3/bin:$PATH
export PATH=~/.dotfiles/bin:$PATH

# Add XCode bin to the `$PATH`
export PATH=$PATH:/Applications/Xcode.app/Contents/Developer/usr/bin
